baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "zh-hans"
title = "閩東語實驗室"
Paginate = 100
[[menu.main]]
    name = "Home"
	weight = -110
	identifier = "home"
	url = "/"
[[menu.main]]
    name = "Projects"
	weight = -100
	identifier = "projects"
	url = "/"
[[menu.main]]
    name = "About Us"
	weight = -70
	identifier = "aboutus"
	url = "/about"
[[menu.main]]
    name = "Contact"
	weight = -80
	identifier = "contact"
	url = "/contact"

	